-- MySQL Script generated by MySQL Workbench
-- 12/14/16 18:52:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema taxi_service
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `taxi_service` ;

-- -----------------------------------------------------
-- Schema taxi_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taxi_service` DEFAULT CHARACTER SET utf8 ;
USE `taxi_service` ;

-- -----------------------------------------------------
-- Table `taxi_service`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`roles` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_idx` (`role` ASC),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`users` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `roles_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles_idx` (`roles_id` ASC),
  INDEX `username_idx` (`username` ASC),
  INDEX `name_idx` (`name` ASC, `last_name` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `taxi_service`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`clients` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_clients_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `taxi_service`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`emails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`emails` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`emails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_emails_users1_idx` (`users_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_emails_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `taxi_service`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`phones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`phones` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`phones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(20) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_phones_users1_idx` (`users_id` ASC),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  CONSTRAINT `fk_phones_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `taxi_service`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`organizations` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`organizations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(256) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_organizations_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_organizations_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `taxi_service`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`drivers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`drivers` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`drivers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `organizations_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_drivers_users1_idx` (`users_id` ASC),
  INDEX `fk_drivers_organizations1_idx` (`organizations_id` ASC),
  CONSTRAINT `fk_drivers_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `taxi_service`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_drivers_organizations1`
    FOREIGN KEY (`organizations_id`)
    REFERENCES `taxi_service`.`organizations` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`cars_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`cars_brands` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`cars_brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`cars_models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`cars_models` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`cars_models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cars_brands_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cars_models_cars_brands1_idx` (`cars_brands_id` ASC),
  INDEX `model_name_idx` (`name` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_cars_models_cars_brands1`
    FOREIGN KEY (`cars_brands_id`)
    REFERENCES `taxi_service`.`cars_brands` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`cars` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `drivers_id` INT NOT NULL,
  `license_plate` VARCHAR(10) NOT NULL,
  `manufacture_year` INT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `cars_brands_id` INT NOT NULL,
  `cars_models_id` INT NOT NULL,
  INDEX `fk_cars_drivers1_idx` (`drivers_id` ASC),
  INDEX `fk_cars_cars_brands1_idx` (`cars_brands_id` ASC),
  INDEX `fk_cars_cars_models1_idx` (`cars_models_id` ASC),
  INDEX `manufacture_year_idx` (`manufacture_year` ASC),
  UNIQUE INDEX `license_plate_UNIQUE` (`license_plate` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cars_drivers1`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `taxi_service`.`drivers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cars_cars_brands1`
    FOREIGN KEY (`cars_brands_id`)
    REFERENCES `taxi_service`.`cars_brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cars_cars_models1`
    FOREIGN KEY (`cars_models_id`)
    REFERENCES `taxi_service`.`cars_models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`points` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`points` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(256) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `name_idx` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`routes` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`routes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(256) NOT NULL,
  `destinations_id` INT NOT NULL,
  `sources_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_routes_points1_idx` (`destinations_id` ASC),
  INDEX `fk_routes_points2_idx` (`sources_id` ASC),
  CONSTRAINT `fk_routes_points1`
    FOREIGN KEY (`destinations_id`)
    REFERENCES `taxi_service`.`points` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_routes_points2`
    FOREIGN KEY (`sources_id`)
    REFERENCES `taxi_service`.`points` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`routes_has_pickup_points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`routes_has_pickup_points` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`routes_has_pickup_points` (
  `routes_id` INT NOT NULL,
  `pickup_points_id` INT NOT NULL,
  PRIMARY KEY (`routes_id`, `pickup_points_id`),
  INDEX `fk_routes_has_pickup_points_pickup_points1_idx` (`pickup_points_id` ASC),
  INDEX `fk_routes_has_pickup_points_routes1_idx` (`routes_id` ASC),
  CONSTRAINT `fk_routes_has_pickup_points_routes1`
    FOREIGN KEY (`routes_id`)
    REFERENCES `taxi_service`.`routes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_routes_has_pickup_points_pickup_points1`
    FOREIGN KEY (`pickup_points_id`)
    REFERENCES `taxi_service`.`points` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`statuses` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`rides`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`rides` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`rides` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `routes_id` INT NOT NULL,
  `drivers_id` INT NOT NULL,
  `arrival_time` DATETIME NOT NULL,
  `departure_time` DATETIME NOT NULL,
  `price` INT NOT NULL,
  `available_seats` INT NOT NULL,
  `cars_id` INT NOT NULL,
  `statuses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rides_routes1_idx` (`routes_id` ASC),
  INDEX `fk_rides_drivers1_idx` (`drivers_id` ASC),
  INDEX `departure_time_idx` (`departure_time` ASC),
  INDEX `price_idx` (`price` ASC),
  INDEX `available_seats_idx` (`available_seats` ASC),
  INDEX `fk_rides_cars1_idx` (`cars_id` ASC),
  INDEX `fk_rides_statuses1_idx` (`statuses_id` ASC),
  CONSTRAINT `fk_rides_routes1`
    FOREIGN KEY (`routes_id`)
    REFERENCES `taxi_service`.`routes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rides_drivers1`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `taxi_service`.`drivers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rides_cars1`
    FOREIGN KEY (`cars_id`)
    REFERENCES `taxi_service`.`cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rides_statuses1`
    FOREIGN KEY (`statuses_id`)
    REFERENCES `taxi_service`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`payment_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`payment_types` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`payment_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`tickets` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rides_id` INT NOT NULL,
  `clients_id` INT NOT NULL,
  `payment_types_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_rides1_idx` (`rides_id` ASC),
  INDEX `fk_tickets_clients1_idx` (`clients_id` ASC),
  INDEX `fk_tickets_payment_types1_idx` (`payment_types_id` ASC),
  CONSTRAINT `fk_tickets_rides1`
    FOREIGN KEY (`rides_id`)
    REFERENCES `taxi_service`.`rides` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tickets_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `taxi_service`.`clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tickets_payment_types1`
    FOREIGN KEY (`payment_types_id`)
    REFERENCES `taxi_service`.`payment_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`ratings` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rating_idx` (`rating` ASC),
  UNIQUE INDEX `rating_UNIQUE` (`rating` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`comments` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(256) NOT NULL,
  `ratings_id` INT NOT NULL,
  `clients_id` INT NOT NULL,
  `organizations_id` INT NOT NULL,
  `drivers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_ratings1_idx` (`ratings_id` ASC),
  INDEX `fk_comments_clients1_idx` (`clients_id` ASC),
  INDEX `fk_comments_organizations1_idx` (`organizations_id` ASC),
  INDEX `fk_comments_drivers1_idx` (`drivers_id` ASC),
  CONSTRAINT `fk_comments_ratings1`
    FOREIGN KEY (`ratings_id`)
    REFERENCES `taxi_service`.`ratings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `taxi_service`.`clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_organizations1`
    FOREIGN KEY (`organizations_id`)
    REFERENCES `taxi_service`.`organizations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_drivers1`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `taxi_service`.`drivers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
